apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gj
  namespace: gj
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gj
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_ssh_secret
      value: gjsecret
  source:
    git:
      # update when code is pushed to a new location
      url: https://github.com/cdelashmutt-pivotal/private-source-example
      ref:
        branch: main